CREATE TABLE TEACHER(
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  age NUMERIC(3) NOT NULL,
  nationality VARCHAR(2) NOT NULL,
  membership VARCHAR(1) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO TEACHER(name, age, nationality, membership) VALUES ('John', 30, 'US', 'Y');

SELECT * FROM TEACHER;
